### ISSUE TITLE
FYI, a use for plaster-yaml

### ISSUE THREAD

**Issue by kpinc** [mardiros/plaster-yaml#15]
Hi,

FYI.  I've [extended pyramid-cookiecutter-starter](https://github.com/kpinc/pyramid-cookiecutter-starter/tree/yaml_config) to use plaster-yaml.  But I have not yet submitted a PR because it will not work unless other PRs, including the ones submitted to plaster-yaml, are resolved.

You may be interested in looking at the code/approach.

**Comment by mardiros** [comment]
Thanks for the ping. I will take a look at the merge requests.

**Comment by mardiros** [comment]
do you  want I release 1.0.2 with this fix  https://github.com/mardiros/plaster-yaml/pull/13 ?

**Comment by kpinc** [comment]
On Wed, 17 Apr 2024 10:16:54 -0700
Guillaume Gauvrit ***@***.***> wrote:

> do you  want I release 1.0.2 with this fix
> https://github.com/mardiros/plaster-yaml/pull/13 ?
> 

I would say yes. It is a problem worth a release.
And this will help with getting yaml into
pyramid-cookiecutter-starter because then code
will then "work more".  (It still needs the
Loader.get_settings() "raw" parameter to actually
work.  But that is contingent upon the plaster
maintainers acceptance.)

FYI:  Looking for you on the web now, so that
we can communicate outside of github, need be.
If you are interested, I am easy to find (in
Chicago and) on the web.  I'd like to comment
on "interpolation", what's not good about it,
and what might replace it.  (IMO, interpolation
needs to go.)

Regards,

Karl ***@***.***>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by mardiros** [comment]
I've release 1.0.2 but did not finish the job properly.
I live in france, so Chicago is a bit far for me :)
Regards
Guillaume
