### ISSUE TITLE
Backwards incompatible change should require a major version change

### ISSUE THREAD

**Issue by kpinc** [mardiros/plaster-yaml#22]
Hi,

Commit 5acf2ecb597958c950db7b2d0b introduced a backwards incompatible change.  Applications that declare a plaster-yaml entry point no longer work, because there are duplicate entry points.

Example error:
```
 File "/home/me/projects/devel/example_app/test_venv/lib/python3.11/site-packages/plaster/loaders.py", line 115, in get_loader
 raise MultipleLoadersFound(
plaster.exceptions.MultipleLoadersFound: Multiple plaster loaders were found for scheme "file+yaml", protocol "wsgi". Please specify a more specific config_uri. Matched loaders: example_app+file+yaml, plaster_yaml+file+yaml
```

Semantic versioning requires that releases containing backwards incompatible changes have a new major version number.  That is, 2.0.

That said, it's a little late now.  Good idea on the change.

**Comment by kpinc** [comment]
At least I think it's a good idea.  I've not thought through the implications.

**Comment by mardiros** [comment]
Agreed. I've made some tests and did not have that issues until today.

Do you want I do a release that rollack the changes and release a major version ?

**Comment by kpinc** [comment]
On Sat, 19 Oct 2024 09:48:51 -0700
Guillaume Gauvrit ***@***.***> wrote:

> Agreed. I've made some tests and did not have that issues until today.
> 
> Do you want I do a release that rollack the changes and release a
> major version ?
> 

I think that would be best.  Anyone who's using the plaster-yaml
will have the problem.  (Unless they've thought ahead and
put version restrictions in their packaging they'll have the problem
anyway.  But at least then it will be their problem. :-)

See also my private-email comment about variable substitution, 
before you make a final decision.

Regards,

Karl ***@***.***>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by kpinc** [comment]
On Sat, 19 Oct 2024 11:54:39 -0500
"Karl O. Pinc" ***@***.***> wrote:

> On Sat, 19 Oct 2024 09:48:51 -0700
> Guillaume Gauvrit ***@***.***> wrote:
> > Do you want I do a release that rollack the changes and release a
> > major version ?

> I think that would be best. 

> See also my private-email comment about variable substitution, 
> before you make a final decision.

I'm thinking that the variable substitution would be
best handled by plaster itself utilizing a template
engine to pre-process the settings file, of whatever
file format, before handing the result back to the
plaster plugin (plaster-yaml in this case).  Meanwhile,
your variable-substitution done in plaster-yaml is
probably not used much, if at all.  And is not so
useful, IMO.  So if the plan (on somebody's part) is
to "do variable substitution right", outside of
plaster-yaml, my thought is to remove the feature
from plaster-yaml.

If you need me to find the issue or email thread or
whatever on the plaster side where the use of a
template engine is floated, I can.  That's where
this thought process is coming from, and I've
some hope that maybe something could happen with
plaster to support this feature.  (The paste-deploy
variable substitution is just too clunky to want
to continue with.)

Regards,

Karl ***@***.***>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by kpinc** [comment]
Meanwhile, anyone who really wants serious variable substitution can pre-process their yaml config file through m4. 

:-)

**Comment by mardiros** [comment]
I've release a 1.1.3 that revert the changes and release a 2.0 to reintroduce the change.

--

Variable substitution, template inclusion would be great.

At the moment, I am trying to achieve that using [a8m envsubst](https://github.com/a8m/envsubst).
It have downside with that because you have to rewrite a file and you may now want write permission
in the directory that run the configuration, where the `%(here)s` substitution can't follow.

to be continued

**Comment by kpinc** [comment]
On Sat, 19 Oct 2024 12:10:52 -0700
Guillaume Gauvrit ***@***.***> wrote:

> I've release a 1.1.3 that revert the changes and release a 2.0 to
> reintroduce the change.
> 
> --
> 
> Variable substitution, template inclusion would be great.
> 
> At the moment, I am trying to achieve that using [a8m
> envsubst](https://github.com/a8m/envsubst). It have downside with
> that because you have to rewrite a file and you may now want write
> permission in the directory that run the configuration, where the
> `%(here)s` substitution can't follow.

I have not thought about where the values that are substituted
should come from.  It's not obvious to me that the environment
is the best, or only, source.  (Then again, I've forgotten
everything I know about the paste-deploy substitution.)

Regardless, if plaster is going to have a substitution mechanism
then that's the mechanism that plaster-yaml should also use.
There has been interest expressed on the plaster side.

Further, it is also clear to me that plaster is what should be
doing the substitution.  It reads every settings file,
regardless of setting file syntax.  And so provides both uniformity,
and a single-source for code; multiple implementations
are not usually desireable.

So I would not implement substitution in plaster-yaml.

Were I to be develop a variable substitution
solution, I would submit it as a PR to plaster itself.
And if you're really determined to use your implementation
I'd maintain a plaster fork.  (Not to say that I'd choose
to fork, but, it is an option available to those who
are very determined/stubborn. :-)

These are my opinions.  I understand yours, and your goals,
may differ.

Regards,

Karl ***@***.***>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein
