### ISSUE TITLE
Documentation still says that the app must declare an entry point

### ISSUE THREAD

**Issue by kpinc** [mardiros/plaster-yaml#23]
Looks like the docs still say an entry point must be declared.  Since commit 5acf2ecb597958c95 declaring an entry point raises an error.

**Comment by mardiros** [comment]
I've remove it here ?

https://github.com/mardiros/plaster-yaml/commit/3be2f194557a79560b5a1ab2af486af3c2d36b9a

Where it is still present ?

**Comment by kpinc** [comment]
On Sat, 19 Oct 2024 09:51:44 -0700
Guillaume Gauvrit ***@***.***> wrote:

> I've remove it here ?
> 
> https://github.com/mardiros/plaster-yaml/commit/3be2f194557a79560b5a1ab2af486af3c2d36b9a
> 
> Where it is still present ?
> 

Well....  My issue report is not so good.   And I didn't
pay close attention to what is now in the README.md.

The vocabulary seems a bit off.  The plaster-yaml 
is now automatically registered, but plaster itself
still requires an entrypoint be declared.

So rather than say the plaster-yaml plugin must be
registered it is probably best to say that usage
requires that plaster be given an entrypoint per:

https://docs.pylonsproject.org/projects/plaster/en/latest/#finding-a-loader

and then go ahead and give examples of how this is done.

(Plus the json registration stuff is is still valid.
That entrypoint is an actual "registration".)

Also, I'm not convinced that the Troubleshooting section
is right -- is the error shown what you get when you
don't have a plaster entrypoint?  I've not thought this
through, or better yet, tried it.

Getting the wording right will take a bit of care.
What's there now is pretty good, and does reflect
the major change.  Improving this should not be
high-priority.

Thanks for the work on this.

Regards,

Karl ***@***.***>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein
