### ISSUE TITLE
Use of pkg_resources makes me nervous 

### ISSUE THREAD

**Issue by kpinc** [mardiros/plaster-yaml#24]
Hi,

My understanding is that pkg_resources is part of setuptools, and so not necessarily something that is universal and will be around forever.

Without knowing what you're doing with
`__import__('pkg_resources').declare_namespace(__name__)`
in your  testcode it seems that maybe pkgutil, possibly with
the use of importlib, would be more future-proof.

Here's a random suggestion in that problem domain
from the internet:

https://stackoverflow.com/questions/1675734/how-do-i-create-a-namespace-package-in-python

Feel free to close this if you don't find it useful.  My past experience with deprecation warnings surrounding pkg_resources may be coloring my judgement.

**Comment by mardiros** [comment]
I agree with you.

I have multiple reason to have done that.

The first one is that I intentionnaly wrote this test to ensure that packages
that use this tricks works.

Actually I don't care much to keep it like that but I have errors at using pkgutils to declare namespace packages.

Maybe I will trash that the whole namespace packages later.

**Comment by kpinc** [comment]
On Sat, 19 Oct 2024 11:37:08 -0700
Guillaume Gauvrit ***@***.***> wrote:

> I agree with you.
> 
> I have multiple reason to have done that.

> Maybe I will trash that the whole namespace packages later.

Fantastic!  Sounds like you know what you're doing.

:)

Regards,

Karl ***@***.***>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein
